### ISSUE TITLE
PSP19SCM07S adding first name

### ISSUE THREAD

**Issue by PSP19SCM07S** [SPM587SP19/SCM587SP19#114]

**Comment by PSP19SCM07S** [comment]
Hi pengyuan li,

my changes were merged into master...so my phase 1 is completed?
Or is there any other thing left to do?

**Comment by SPM587SP19** [comment]
If you finish all the requirements of phase I listed in the assignment#5. Then nothing left is for you now.

**Comment by PSP19SCM07S** [comment]
So the screenshot part is for phase 2....correct?
